name: torrstv
description: "All movies in one app"
publish_to: 'none'

version: 1.0.0+14

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  http: ^1.6.0
  go_router: ^17.0.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  path: ^1.9.1
  file_picker: ^10.3.6
  flutter_cache_manager: ^3.4.1
  flutter_svg: ^2.2.2
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  media_kit: ^1.2.2
  media_kit_video: ^2.0.0
  media_kit_libs_video: ^1.0.7

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
